### ISSUE TITLE
Error: Cannot find module '../../../build/Release/demangle'

### ISSUE THREAD

**Issue by jburnham** [uber/node-stap#12]
```
module.js:340
    throw err;
          ^
Error: Cannot find module '../../../build/Release/demangle'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/node-stap/lib/elf-atos/loaders/elf_loader.js:29:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I made sure to do the npm install and systemtap and kernel headers are installed. I feel like there's a missing step here or I'm missing something.

Thanks

**Comment by Raynos** [comment]
Is it because `../../../build/Debug` exists ?

**Comment by danielheller** [comment]
@jburnham what command did you run?

**Comment by jburnham** [comment]
node cmd/torch.js $PID text 10

**Comment by jburnham** [comment]
Is there a step I need to do to compile the demangle code?

**Comment by danielheller** [comment]
There should not be.  @Raynos's question is a good one—does that directory exist?  Do you have a BUILDTYPE environment variable set?

**Comment by jburnham** [comment]
ubuntu@server:~/node-stap/lib/elf-atos/loaders$ ls -l ../../../build
ls: cannot access ../../../build: No such file or directory

That ../../../ should be the root of the project and there is no build directory there. 

BUILDTYPE is not set to anything

**Comment by danielheller** [comment]
Curious.  I've tried this on a few types of systems and haven't seen a failure to create ${projroot/{build/.  If you're still trying, would you mind gist'ing up your "npm install" output and npm and node versions?  Thanks for your help on this as an early adopter!

**Comment by sh1mmer** [comment]
If the nod binary was compiled with Debug on then installing / compiling with NPM using that will put binaries into Debug not Release

**Comment by jburnham** [comment]
So it looks like there were two things that I needed to do to fix this.

1) Fix a local issue specific to my environment with the npm install (not relevant to this project).
2) I needed to apt-get install build-essential to get the compilation tools necessary to finish the install

Now the script works but fails on something else. This is probably because I am using the systemtap that comes with ubuntu 14.04 (2.3 instead of 2.7 like the README states). 

```
ubuntu@server:~/node-stap$ sudo node cmd/torch.js 6347 raw 10 > ../raw.txt
Sampling 6347 for 10s, outputting raw.

[stap stderr] make[1]: *** Deleting file `/tmp/stap8vZ6Fa/stapconf_83f8d8d871e76f8bfc186d05a6524d9d_687.h'
make[1]: *** [/tmp/stap8vZ6Fa/stapconf_83f8d8d871e76f8bfc186d05a6524d9d_687.h] Terminated
make: *** [_module_/tmp/stap8vZ6Fa] Terminated
WARNING: kbuild exited with signal: 15 (Terminated)
Pass 4: compilation failed.  [man error::pass4]
```

What environments are you running this in? Did you install a backport version of systemtap?

**Comment by makenova** [comment]
@jburnham did you make any progress on this, I'm in a similar situation.

**Comment by danielheller** [comment]
I've pushed a quick fix that I think should address this; mind trying again?

**Comment by makenova** [comment]
I think that fixed it!
I'm getting output now but there is an error in my `flame.html`(likely unrelated).

**Comment by makenova** [comment]
@danielheller, I spoke too soon.
I get some output with the `flame` option but when I try to view the `flame.html` in chrome, all I see is something similar to the following with no flamegraph:

> ## Flame graph
>
> Hover over a block for summary information. Click a block for details. [Reset view]()

With the `raw` option, the `raw.txt` is completely empty.

Pardon the false positive.

**Comment by danielheller** [comment]
@makenova that is consistent with sampling a process which is not doing anything.  Can you confirm with top that the process you're sampling is reasonably active on-CPU?

This discussion is, however, a bit off-topic for this issue. @makenova if you confirm that the process you're sampling is actively consuming CPU, then please open an issue with the richest reproduction steps you can and I will eagerly debug.

 @jburnham If I understand the issue you're hitting correctly, it would affect any usage of a native add-on, and is therefore somewhat outside the scope of a readme for this specific project.  I'm therefore going to mark this one as resolved.  If I'm incorrect and this is an issue specific to node-stap, then apologies and please re-open.
