### ISSUE TITLE
Can you expand on your README.md?

### ISSUE THREAD

**Issue by Redsandro** [uber/node-stap#16]
I have this output and no clue what step I missed.

```
$ sudo torch 30397 flame 10 > /tmp/flame.html
Sampling 30397 for 10s, outputting flame.

[stap stderr] make[1]: *** Deleting file `/tmp/stapD6o4Q9/stapconf_4f29438011f21a8f335aea1dd50e0865_687.h'

[stap stderr] make[1]: *** [/tmp/stapD6o4Q9/stapconf_4f29438011f21a8f335aea1dd50e0865_687.h] Terminated
make: *** [_module_/tmp/stapD6o4Q9] Terminated
WARNING: kbuild exited with signal: 15 (Terminated)
Pass 4: compilation failed.  [man error::pass4]

Systemtap exited unexpectedly { type: 1 }
Exiting due to profiling failure.
```

**Comment by danielheller** [comment]
Are you using current master?  I fixed a bug which had symptoms like this.

**Comment by Redsandro** [comment]
I used `npm install node-stap`. Does node-step require the node internal symbol exporter `--perf-basic-prof`?

In that case, I think the problem might be node 0.10.x I am using. Node outputs debugging symbols since 0.11.x. I cannot get 0.11 or 0.12 to work because node-gyp fails to build my modules then.

**Comment by danielheller** [comment]
It does not require --perf-basic prof.  It looks like I just failed to "npm publish" my fix.  I've rectified that now.  Thanks for raising this!

**Comment by Redsandro** [comment]
The new version works, but the flamegraph is consistently empty.

```
$ sudo torch 5220 flame 10 > /tmp/flame.html
Sampling 5220 for 10s, outputting flame.

$ chromium-browser /tmp/flame.html
Created new window in existing browser session.
```

There is no warning or error output. Any idea what I could check?

**Comment by Redsandro** [comment]
`raw` outputs a million of these:

```
[0x8027000008 in unknown binary]:[native]
[0x8027000008 in unknown binary]:[native]
[0x8027000008 in unknown binary]:[native]
[0x8027000008 in unknown binary]:[native]
[0x8027000008 in unknown binary]:[native]
[0x8027000008 in unknown binary]:[native]
```

and occasionally something like this:

```
[0x8027000008 in unknown binary]:[native]
   1
[internal frame]
[entry frame]
[0x7fa304dd222c in libv8.so.3.14.5]:[native]
[0x3fc92c506160 in unknown binary]:[native]
[0x92404f4900000000 in unknown binary]:[native]
[0x1900008126000000 in unknown binary]:[native]
[0x8027000008 in unknown binary]:[native]
```

**Comment by danielheller** [comment]
What are the version of the "node" in your path and of the process you are sampling (probably but not necessarily the same)?

**Comment by Redsandro** [comment]
Both `v0.10.25`.

**Comment by danielheller** [comment]
That is certainly peculiar!  Are you running against a complex program?
Would you mind trying with something very simple and see what happens, and
if it reproduces, post the program so I try it?  You could use, for
example, the program from the README text example.

Also, what kernel/systemtap versions are you using?

**Comment by Redsandro** [comment]
```
$ nano test.js
$ node test.js  > /dev/null & 
[1] 21384
$ sudo torch 21384 text 10
sudo: torch: command not found
$ sudo npm install -g node-stap
$ sudo torch 21384 text 10
Sampling 21384 for 10s, outputting text.

SystemTap not installed!
Exiting due to profiling failure.
$ sudo apt-get install systemtap
$ sudo torch 21384 text 10
Sampling 21384 for 10s, outputting text.

1 [0x34afa1f4d590 in unknown binary]:[native]
  1 [0x7f93231306e0 in /usr/lib/libv8.so.3.14.5]:[native]
1 [0x34afa1f66788 in unknown binary]:[native]
  1 [0x7f9323004612 in /usr/lib/libv8.so.3.14.5]:[native]
1 [0x34afa0f15710 in unknown binary]:[native]
  1 [0x7f9322ff9e49 in /usr/lib/libv8.so.3.14.5]:[native]
1 [0x34afa0dc83b8 in unknown binary]:[native]
  1 [0x7f93231306e0 in /usr/lib/libv8.so.3.14.5]:[native]
1 [0x34afa0deb638 in unknown binary]:[native]
  1 [0x7f93230c7b12 in /usr/lib/libv8.so.3.14.5]:[native]
1 [0x34afa1f19228 in unknown binary]:[native]
  1 [0x7f93231306e0 in /usr/lib/libv8.so.3.14.5]:[native]
1 [0x7f9322fa3826 in /usr/lib/libv8.so.3.14.5]:[native]
1 [0x34afa1c00000 in unknown binary]:[native]
  1 [0x34afa1d00000 in unknown binary]:[native]
    1 [0x34afa1e00000 in unknown binary]:[native]
      1 [0x34afa1f00000 in unknown binary]:[native]
        1 [0x170e7b0 in unknown binary]:[native]
          1 [0x34afa1c00000 in unknown binary]:[native]
            1 [0x34afa1d00000 in unknown binary]:[native]
              1 [0x34afa1e00000 in unknown binary]:[native]
                1 [0x34afa1f00000 in unknown binary]:[native]
                  1 [0x170e7b0 in unknown binary]:[native]
                    1 [0x34afa1c00000 in unknown binary]:[native]
                      1 [0x34afa1d00000 in unknown binary]:[native]
                        1 [0x34afa1e00000 in unknown binary]:[native]
                          1 [0x34afa1f00000 in unknown binary]:[native]
                            1 [0x170e7b0 in unknown binary]:[native]
                              1 [0x34afa1c00000 in unknown binary]:[native]
                                1 [0x34afa1d00000 in unknown binary]:[native]
                                  1 [0x34afa1e00000 in unknown binary]:[native]
                                    1 [0x34afa1f00000 in unknown binary]:[native]
                                      1 [0x170e7b0 in unknown binary]:[native]
                                        1 [0x34afa1c00000 in unknown binary]:[native]
                                          1 [0x34afa1d00000 in unknown binary]:[native]
                                            1 [0x34afa1e00000 in unknown binary]:[native]
                                              1 [0x34afa1f00000 in unknown binary]:[native]
                                                1 [0x170e7b0 in unknown binary]:[native]
                                                  1 [0x34afa1c00000 in unknown binary]:[native]
                                                    1 [0x34afa1d00000 in unknown binary]:[native]
                                                      1 [0x34afa1e00000 in unknown binary]:[native]
                                                        1 [0x34afa1f00000 in unknown binary]:[native]
                                                          1 [0x170e7b0 in unknown binary]:[native]
                                                            1 [0x34afa1c00000 in unknown binary]:[native]
                                                              1 [0x34afa1d00000 in unknown binary]:[native]
                                                                1 [0x34afa1e00000 in unknown binary]:[native]
                                                                  1 [0x34afa1f00000 in unknown binary]:[native]
                                                                    1 [0x170e7b0 in unknown binary]:[native]
                                                                      1 [0x34afa1c00000 in unknown binary]:[native]
                                                                        1 [0x34afa1d00000 in unknown binary]:[native]
                                                                          1 [0x34afa1e00000 in unknown binary]:[native]
                                                                            1 [0x34afa1f00000 in unknown binary]:[native]
                                                                              1 [0x170e7b0 in unknown binary]:[native]
                                                                                1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                  1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                    1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                      1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                        1 [0x170e7b0 in unknown binary]:[native]
                                                                                          1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                            1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                              1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                  1 [0x170e7b0 in unknown binary]:[native]
                                                                                                    1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                      1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                        1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                          1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                            1 [0x170e7b0 in unknown binary]:[native]
                                                                                                              1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                  1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                    1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                      1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                        1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                          1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                            1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                              1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                  1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                    1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                      1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                                        1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                          1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                            1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                              1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                                1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                                                  1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                                    1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                                      1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                                        1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                                          1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                                                            1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                                              1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                                                1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                                                  1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                                                    1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                                                                      1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                                                        1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                                                          1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                                                            1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                                                              1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                                                                                1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                                                                  1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                                                                    1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                                                                      1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                                                                        1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                                                                                          1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                                                                            1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                                                                              1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                                                                                1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                                                                                  1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                                                                                                    1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                                                                                      1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                                                                                        1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                                                                                          1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                                                                                            1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                                                                                                              1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                                                                                                1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                                                                                                  1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                                                                                                    1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                                                                                                      1 [0x34afa1e00000 in unknown binary]:[native]
                                                                                                                                                                                                                        1 [0x34afa1f00000 in unknown binary]:[native]
                                                                                                                                                                                                                          1 [0x170e7b0 in unknown binary]:[native]
                                                                                                                                                                                                                            1 [0x34afa1c00000 in unknown binary]:[native]
                                                                                                                                                                                                                              1 [0x34afa1d00000 in unknown binary]:[native]
                                                                                                                                                                                                                                1 [0x34afa1e00000 in unknown binary]:[native]
                      	
```

**Comment by danielheller** [comment]
Sorry, can you please include in your example the text of the node program
and the output of:

uname -a
stap --version
node --version

I just want to be 100% sure that I am understanding the exact scenario that
you are running.

Cheers,
Dan

On Wed, May 6, 2015 at 11:42 AM, Sander AKA Redsandro <
notifications@github.com> wrote:

> $ nano test.js
> $ node test.js  > /dev/null &
> [1] 21384
> $ sudo torch 21384 text 10
> sudo: torch: command not found
> $ sudo npm install -g node-stap
> $ sudo torch 21384 text 10
> Sampling 21384 for 10s, outputting text.
>
> SystemTap not installed!
> Exiting due to profiling failure.
> $ sudo apt-get install systemtap
> $ sudo torch 21384 text 10
> Sampling 21384 for 10s, outputting text.
>
> 1 [0x34afa1f4d590 in unknown binary]:[native]
>   1 [0x7f93231306e0 in /usr/lib/libv8.so.3.14.5]:[native]
> 1 [0x34afa1f66788 in unknown binary]:[native]
>   1 [0x7f9323004612 in /usr/lib/libv8.so.3.14.5]:[native]
> 1 [0x34afa0f15710 in unknown binary]:[native]
>   1 [0x7f9322ff9e49 in /usr/lib/libv8.so.3.14.5]:[native]
> 1 [0x34afa0dc83b8 in unknown binary]:[native]
>   1 [0x7f93231306e0 in /usr/lib/libv8.so.3.14.5]:[native]
> 1 [0x34afa0deb638 in unknown binary]:[native]
>   1 [0x7f93230c7b12 in /usr/lib/libv8.so.3.14.5]:[native]
> 1 [0x34afa1f19228 in unknown binary]:[native]
>   1 [0x7f93231306e0 in /usr/lib/libv8.so.3.14.5]:[native]
> 1 [0x7f9322fa3826 in /usr/lib/libv8.so.3.14.5]:[native]
> 1 [0x34afa1c00000 in unknown binary]:[native]
>   1 [0x34afa1d00000 in unknown binary]:[native]
>     1 [0x34afa1e00000 in unknown binary]:[native]
>       1 [0x34afa1f00000 in unknown binary]:[native]
>         1 [0x170e7b0 in unknown binary]:[native]
>           1 [0x34afa1c00000 in unknown binary]:[native]
>             1 [0x34afa1d00000 in unknown binary]:[native]
>               1 [0x34afa1e00000 in unknown binary]:[native]
>                 1 [0x34afa1f00000 in unknown binary]:[native]
>                   1 [0x170e7b0 in unknown binary]:[native]
>                     1 [0x34afa1c00000 in unknown binary]:[native]
>                       1 [0x34afa1d00000 in unknown binary]:[native]
>                         1 [0x34afa1e00000 in unknown binary]:[native]
>                           1 [0x34afa1f00000 in unknown binary]:[native]
>                             1 [0x170e7b0 in unknown binary]:[native]
>                               1 [0x34afa1c00000 in unknown binary]:[native]
>                                 1 [0x34afa1d00000 in unknown binary]:[native]
>                                   1 [0x34afa1e00000 in unknown binary]:[native]
>                                     1 [0x34afa1f00000 in unknown binary]:[native]
>                                       1 [0x170e7b0 in unknown binary]:[native]
>                                         1 [0x34afa1c00000 in unknown binary]:[native]
>                                           1 [0x34afa1d00000 in unknown binary]:[native]
>                                             1 [0x34afa1e00000 in unknown binary]:[native]
>                                               1 [0x34afa1f00000 in unknown binary]:[native]
>                                                 1 [0x170e7b0 in unknown binary]:[native]
>                                                   1 [0x34afa1c00000 in unknown binary]:[native]
>                                                     1 [0x34afa1d00000 in unknown binary]:[native]
>                                                       1 [0x34afa1e00000 in unknown binary]:[native]
>                                                         1 [0x34afa1f00000 in unknown binary]:[native]
>                                                           1 [0x170e7b0 in unknown binary]:[native]
>                                                             1 [0x34afa1c00000 in unknown binary]:[native]
>                                                               1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                 1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                   1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                     1 [0x170e7b0 in unknown binary]:[native]
>                                                                       1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                         1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                           1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                             1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                               1 [0x170e7b0 in unknown binary]:[native]
>                                                                                 1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                   1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                     1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                       1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                         1 [0x170e7b0 in unknown binary]:[native]
>                                                                                           1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                             1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                               1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                 1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                   1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                     1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                       1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                         1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                           1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                             1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                               1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                 1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                   1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                     1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                       1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                         1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                           1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                             1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                               1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                 1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                   1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                     1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                       1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                                         1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                           1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                             1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                               1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                                 1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                                                   1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                                     1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                                       1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                                         1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                                           1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                                                             1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                                               1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                                                 1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                                                   1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                                                     1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                                                                       1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                                                         1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                                                           1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                                                             1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                                                               1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                                                                                 1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                                                                   1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                                                                     1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                                                                       1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                                                                         1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                                                                                           1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                                                                             1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                                                                               1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                                                                                 1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                                                                                   1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                                                                                                     1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                                                                                       1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                                                                                         1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                                                                                           1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                                                                                             1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                                                                                                               1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                                                                                                 1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                                                                                                   1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                                                                                                     1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                                                                                                       1 [0x34afa1e00000 in unknown binary]:[native]
>                                                                                                                                                                                                                         1 [0x34afa1f00000 in unknown binary]:[native]
>                                                                                                                                                                                                                           1 [0x170e7b0 in unknown binary]:[native]
>                                                                                                                                                                                                                             1 [0x34afa1c00000 in unknown binary]:[native]
>                                                                                                                                                                                                                               1 [0x34afa1d00000 in unknown binary]:[native]
>                                                                                                                                                                                                                                 1 [0x34afa1e00000 in unknown binary]:[native]
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uber/node-stap/issues/16#issuecomment-99400665>.
>

**Comment by Redsandro** [comment]
```
$ cat test.js 
while(true) {
    console.log("Hello!");
}

$ uname -a
Linux RedFenix 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ stap --version
Systemtap translator/driver (version 2.3/0.158, Debian version 2.3-1ubuntu1 (trusty))
Copyright (C) 2005-2013 Red Hat, Inc. and others
This is free software; see the source for copying conditions.
enabled features: AVAHI LIBSQLITE3 NSS TR1_UNORDERED_MAP NLS

$ node --version
v0.10.25
```
